let db;
let editor;
let currentMission = 0;

const missions = [
  {
    question: "🎯 Mission 1: How many sales did Dwight Schrute make?",
    check: (result) => result.length === 5
  },
  {
    question: "🎯 Mission 2: What is the total revenue generated by Jim Halpert?",
    check: (result) => result[0] && result[0][0] === 4340
  },
  {
    question: "🎯 Mission 3: List all unique products sold by Angela Martin.",
    check: (result) => {
      const expected = new Set(["Folders", "Paper", "Envelopes", "Notebooks"]);
      const actual = new Set(result.map(row => row[0]));
      return expected.size === actual.size && [...expected].every(p => actual.has(p));
    }
  },
  {
    question: "🎯 Mission 4: Who sold paper to Costco?",
    check: (result) => result.map(row => row[0]).includes("Dwight Schrute")
  },
  {
    question: "🎯 Mission 5: Which employee made the largest single sale?",
    check: (result) => result[0] && result[0][0] === "Dwight Schrute"
  }
];

function showMission(index) {
  const mission = missions[index];
  document.getElementById("mission").textContent = mission.question;
}

function displayResults(results) {
  const output = document.getElementById("output");
  output.innerHTML = "";

  if (!results || results.length === 0) {
    output.innerHTML = "<p>No results.</p>";
    return;
  }

  const table = document.createElement("table");
  const thead = document.createElement("thead");
  const headerRow = document.createElement("tr");

  results.columns.forEach(col => {
    const th = document.createElement("th");
    th.textContent = col;
    headerRow.appendChild(th);
  });

  thead.appendChild(headerRow);
  table.appendChild(thead);

  const tbody = document.createElement("tbody");

  results.values.forEach(row => {
    const tr = document.createElement("tr");
    row.forEach(cell => {
      const td = document.createElement("td");
      td.textContent = cell;
      tr.appendChild(td);
    });
    tbody.appendChild(tr);
  });

  table.appendChild(tbody);
  output.appendChild(table);
}

async function initDatabase() {
  const SQL = await initSqlJs({
    locateFile: filename => `https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.6.2/${filename}`
  });

  db = new SQL.Database();

  const response = await fetch("https://raw.githubusercontent.com/TerminalQuest489/Dunder-Mifflin-Quest/main/data/dunder_mifflin_sales.json");
  const json = await response.json();

  db.run(`
    CREATE TABLE sales (
      employee TEXT,
      product TEXT,
      amount INTEGER,
      client TEXT
    );
  `);

  const stmt = db.prepare("INSERT INTO sales VALUES (?, ?, ?, ?)");

  json.sales.forEach(({ employee, product, amount, client }) => {
    stmt.run([employee, product, amount, client]);
  });

  stmt.free();

  editor = CodeMirror.fromTextArea(document.getElementById("editor"), {
    mode: "text/x-sql",
    theme: "dracula",
    lineNumbers: true,
    viewportMargin: Infinity
  });

  showMission(currentMission);
}

function runQuery() {
  const query = editor.getValue();

  try {
    const results = db.exec(query);
    displayResults(results[0]);

    if (missions[currentMission].check(results[0].values)) {
      alert("✅ Mission Complete!");
      currentMission++;
      if (currentMission < missions.length) {
        showMission(currentMission);
      } else {
        document.getElementById("mission").textContent = "🎉 All missions complete!";
      }
    }
  } catch (e) {
    document.getElementById("output").textContent = "❌ Error: " + e.message;
  }
}

document.getElementById("run-btn").addEventListener("click", runQuery);
initDatabase();
